name: portfolio_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0 # add this dependency
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # or latest version

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#121212"
  image: assets/images/logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"  # <-- your logo path
  adaptive_icon_background: "#121212"   # optional for Android 8.0+
  adaptive_icon_foreground: "assets/images/logo.png"