// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrXcq-_D0QWoxnrMuxK3uGYuD7f4wh-E',
    appId: '1:743943051162:web:d455ec6db2c52110d54c23',
    messagingSenderId: '743943051162',
    projectId: 'trackfolio-ac352',
    authDomain: 'trackfolio-ac352.firebaseapp.com',
    storageBucket: 'trackfolio-ac352.firebasestorage.app',
    measurementId: 'G-2642BDD7W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6C5ms8XAiU-bogiWBAPdSbQMf-ho9GOc',
    appId: '1:743943051162:android:30b9cb5b512984a5d54c23',
    messagingSenderId: '743943051162',
    projectId: 'trackfolio-ac352',
    storageBucket: 'trackfolio-ac352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPN1tVtBv1Y8oUj1WheYAPDynIPzvctD0',
    appId: '1:743943051162:ios:5cd4d3c538355facd54c23',
    messagingSenderId: '743943051162',
    projectId: 'trackfolio-ac352',
    storageBucket: 'trackfolio-ac352.firebasestorage.app',
    iosBundleId: 'com.example.portfolioManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPN1tVtBv1Y8oUj1WheYAPDynIPzvctD0',
    appId: '1:743943051162:ios:5cd4d3c538355facd54c23',
    messagingSenderId: '743943051162',
    projectId: 'trackfolio-ac352',
    storageBucket: 'trackfolio-ac352.firebasestorage.app',
    iosBundleId: 'com.example.portfolioManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUrXcq-_D0QWoxnrMuxK3uGYuD7f4wh-E',
    appId: '1:743943051162:web:f71dff815f8a2761d54c23',
    messagingSenderId: '743943051162',
    projectId: 'trackfolio-ac352',
    authDomain: 'trackfolio-ac352.firebaseapp.com',
    storageBucket: 'trackfolio-ac352.firebasestorage.app',
    measurementId: 'G-BM9XJWPF3T',
  );
}
